last_query: 0
solr_core: arclight-1.4_dev
solr_url: https://solr2020.library.albany.edu:8984/solr
cache_expiration: 3600
metadata:
- ssm:
  - date_published
  - date_digitized
  - extent
- ssim:
  - legacy_id
  - resource_type
  - coverage
  - preservation_package
  - creator
  - contributor
  - preservation_format
  - source
- tesm:
  - processing_activity
- tesim:
  - description