cache_expiration: 86400
last_query: 0
metadata:
- ss:
  - replay_content
- ssi:
  - date_uploaded
  - replay_pdf
- ssm:
  - date_digitized
  - extent
- ssim:
  - legacy_id
  - resource_type
  - coverage
  - preservation_package
  - creator
  - contributor
  - preservation_format
  - source
- tesm:
  - processing_activity
- tesim:
  - description
solr_core: arclight-1.6
solr_url: https://solr2020.library.albany.edu:8984/solr
