version: '3.1'

services:
  flask1:
    image: processing
    container_name: processing-dev
    ports:
      - '5000:5000'
    environment:
      - TZ=America/New_York
    env_file:
      - .env
    volumes:
      - '.:/code'
      - '..\flask_processing_app_testing\Archives:/Archives'
      - '..\flask_processing_app_testing\automated\DigitizationExtentTracker:/DigitizationExtentTracker'
      - '..\flask_processing_app_testing\backlog:/backlog'
      - '..\flask_processing_app_testing\ingest:/ingest'
      - '..\flask_processing_app_testing\SPE_DAO:/SPE_DAO'
      - '..\flask_processing_app_testing\processing_logs:/logs'
      - '..\flask_processing_app_testing\ndpaList.txt:/ndpaList.txt'
    working_dir: /code
    command: >
      bash -c "export FLASK_DEBUG="1" &&
              flask run --host=0.0.0.0"