version: '3.1'

services:
  flask1:
    image: python:3.9-slim-buster
    ports:
      - '5000:5000'
    environment:
      - TZ=America/New_York
    volumes:
      - '.:/code'
      - '..\flask_processing_app_testing\Archives:/Archives'
      - '..\flask_processing_app_testing\automated:/automated'
      - '..\flask_processing_app_testing\backlog:/backlog'
      - '..\flask_processing_app_testing\ingest:/ingest'
      - '..\flask_processing_app_testing\processing_logs:/logs'
    working_dir: /code
    command: >
      bash -c "cp /code/.archivessnake.yml ~ &&
              cp /code/.hyrax.yml ~ &&
              apt update &&
              apt install apt-transport-https gnupg wget aptitude -y &&
              echo 'deb [trusted=yes] https://notesalexp.org/tesseract-ocr5/buster/ buster main' >> /etc/apt/sources.list &&
              apt update -oAcquire::AllowInsecureRepositories=true &&
              apt install notesalexp-keyring -oAcquire::AllowInsecureRepositories=true -y &&
              wget -O - https://notesalexp.org/debian/alexp_key.asc | apt-key add - &&
              apt update &&
              aptitude install tesseract-ocr -y &&
              apt install tzdata -y &&
              apt install rsync imagemagick -y &&
              ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&
              pip install -r requirements.txt &&
              export FLASK_DEBUG="1" &&
              flask run --host=0.0.0.0"