version: '3.1'

services:
  flask1:
    image: processing
    hostname: aspace-dev.library.albany.edu
    network_mode: "host"
    ports:
      - '0.0.0.0:5000:5000'
    volumes:
      - '..\flask_processing_app_testing\Archives:/Archives'
      - '..\flask_processing_app_testing\automated:/automated'
      - '..\flask_processing_app_testing\backlog:/backlog'
      - '..\flask_processing_app_testing\ingest:/ingest'
      - '..\flask_processing_app_testing\processing_logs:/logs'
    tty: true
    stdin_open: true
    build: .
