version: '3.1'

services:
  flask1:
    image: python:3.11.2-slim-buster
    ports:
      - '5000:5000'
    environment:
      - TZ=America/New_York
    volumes:
      - '.:/code'
      - '..\flask_processing_app_testing\Archives:/Archives'
      - '..\flask_processing_app_testing\automated:/automated'
      - '..\flask_processing_app_testing\backlog:/backlog'
      - '..\flask_processing_app_testing\ingest:/ingest'
      - '..\flask_processing_app_testing\processing_logs:/logs'
    working_dir: /code
    command: >
      bash -c "pip install -r requirements.txt &&
              cp /code/.archivessnake.yml ~ &&
              cp /code/.hyrax.yml ~ &&
              apt update &&
              apt install tzdata -y &&
              apt install imagemagick -y &&
              apt install tesseract-ocr -y &&
              apt install rsync -y &&
              ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&
              export FLASK_DEBUG="1" &&
              flask run --host=0.0.0.0"