version: '3.1'

services:
  flask1:
    image: processing
    hostname: aspace-dev.library.albany.edu
    network_mode: "host"
    ports:
      - '0.0.0.0:5000:5000'
    volumes:
      - '/media/Library/SPE_Processing/processing_sandbox/Archives:/Archives'
      - '/media/Library/SPE_Processing/processing_sandbox/automated:/automated'
      - '/media/Library/SPE_Processing/processing_sandbox/backlog:/backlog'
      - '/media/Library/SPE_Processing/processing_sandbox/ingest:/ingest'
      - '/media/Library/SPE_Processing/processing_sandbox/logs:/logs'
    tty: true
    stdin_open: true
    build: .
